name: Release Module

on:
    workflow_dispatch:

    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            #
            # Initialize
            #
            - name: Checkout Repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  registry-url: 'https://registry.npmjs.org'
                  scope: '@og-modules'

            #
            # Set version number and other metadata
            #
            - name: 'Get Previous tag'
              id: previoustag
              uses: 'WyriHaximus/github-action-get-previous-tag@v1'

            - name: Get version from module.json
              id: version
              uses: notiz-dev/github-action-json-property@release
              with:
                  path: 'module.json'
                  prop_path: 'version'

            - name: Set versions variables
              id: versions
              run: |
                  previous="${{ steps.previoustag.outputs.tag }}"
                  current="v${{ steps.version.outputs.prop }}"
                  echo "::set-output name=previous::$previous"
                  echo "::set-output name=current::$current"

            - name: Output values
              run: |
                  echo "Previous: ${{ steps.versions.outputs.previous }}"
                  echo "Current: ${{ steps.versions.outputs.current }}"
                  echo "Should release? ${{ steps.versions.outputs.previous != steps.versions.outputs.current }}"

            - name: Substitute Manifest and Download Links For Versioned Ones
              uses: microsoft/variable-substitution@v1
              with:
                  files: 'module.json'
              env:
                  url: https://github.com/${{ github.repository }}
                  manifest: https://github.com/${{ github.repository }}/releases/latest/download/module.json
                  download: https://github.com/${{ github.repository }}/releases/download/v${{ steps.version.outputs.prop }}/module.zip
              if: ${{ steps.versions.outputs.previous != steps.versions.outputs.current }}

            - name: Replace the package.json version with the module.json one
              uses: microsoft/variable-substitution@v1
              with:
                  files: 'package.json'
              env:
                  version: ${{ steps.version.outputs.prop }}
              if: ${{ steps.versions.outputs.previous != steps.versions.outputs.current }}

            #
            # Build
            #
            - name: Install dependencies
              run: npm i
              if: ${{ steps.versions.outputs.previous != steps.versions.outputs.current }}

            - name: Build the module
              run: npm run build
              if: ${{ steps.versions.outputs.previous != steps.versions.outputs.current }}

            #
            # Release to GitHub and Publish to NPM registry
            #
            - name: Create Module Archive from the dist directory
              run: cd dist && zip -r ../module.zip . && cd ..
              if: ${{ steps.versions.outputs.previous != steps.versions.outputs.current }}

            - name: Create the GitHub release
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: v${{ steps.version.outputs.prop }}
                  files: |
                      module.zip
                      module.json
              if: ${{ steps.versions.outputs.previous != steps.versions.outputs.current }}

            - name: Publish to the NPM registry
              run: cd dist && npm publish --access=public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              if: ${{ steps.versions.outputs.previous != steps.versions.outputs.current }}
